
################################################################################
# File paths
################################################################################

variable "ec2_config_file" {
  type = string
  default = "config_docker.sh"
  description = "The path to the shell script used to configure the EC2 instance once started."
}

variable "ec2_pem_pub_file" {
  type = string
  default = "output.pem.pub"
  description = "The path to the public PEM key used to upload the ec2_config_file to the EC2 instance."
}

variable "prepro_docker_image" {
  type = string
  default = "valkea/ungdc_prefect_agent:latest"
  description = "The path to the Docker image to start on the Preprocessing EC2 instance."
}

################################################################################
# EC2 for preprocessing (data-collection / data preparation)
################################################################################

variable "instance_type" {
  type    = string
  default = "t2.micro"
}

variable "instance_ami" {
  type = string
  default = "ami-0694d931cee176e7d" # Ubuntu Server 22.04 LTS (64-bit (x86))
  description = "Instance AMI image to use, by default Ubuntu 22.04 LTS"
}

variable "spot_instance" {
  type = string
  default = "true"
  description = "This value is true if we want to use a spot instance instead of a regular one"
}

variable "spot_price" {
  type = string
  default = "0.0060"
  description = "Maximum price to pay for spot instance"
}

variable "spot_type" {
  type = string
  default = "persistent"
# default = "one-time"
  description = "Spot instance type, this value only applies for spot instance type."
}

################################################################################
# AWS Scheduler to control the preprocessing EC2 instance runtime
################################################################################

variable "scheduler_start_cron" {
  type = string
  default = "cron(0 * ? * MON-FRI *)"
  description = "The (AWS) cron expession for stopping the EC2 instance for the data-collection & indexing"
}

variable "scheduler_stop_cron" {
  type = string
  default = "cron(5 * ? * MON-FRI *)"
  description = "The (AWS) cron expession for starting the EC2 instance for the data-collection & indexing"
}

variable "scheduler_cron_timezine" {
  type = string
  default = "UTC"
  description = "The timezone for the start and stop cron expressions"
}

################################################################################
# S3 to store data generated by the preprocessing EC2 instance
################################################################################

variable "s3_instance" {
  type = string
  default = "false"
  description = "This value is true if we want to use an S3 instance"
}

variable "s3_name" {
  type = string
  default = "omdena-un-gdc-bucket-02"
  description = "This value used as S3 instance name"
}

variable "s3_force_destroy" {
  type = string
  default = "false"
  description = "This value is true if we want to destroy the S3 instance EVEN if there is content inside"
}
